### ISSUE TITLE
naxsi error when change password

### ISSUE THREAD

**Issue by habnai** [hwdsl2/setup-ghost-blog#10]
i can not change password when i install with Naxsi in Debian 8 and in Centos 7,all work ok only problem when change password i get this in error.log :  
`2016/11/14 22:19:41 [error] 3346#0: *18 NAXSI_FMT: ip=x.my.ipx&server=domain.com&uri=/ghost/api/v0.1/users/password/&learning=0&vers=0.55&total_processed=20&total_blocked=3&block=1&cscore0=$SQL&sco$`

**Comment by hwdsl2** [comment]
@habnai Can you post the entire error line? It was cut off at `sco$`.

**Comment by habnai** [comment]
`2016/11/14 22:19:41 [error] 3346#0: *18 NAXSI_FMT: ip=home-ip&server=domain.com&uri=/ghost/api/v0.1/users/password/&learning=0&vers=0.55&total_processed=20&total_blocked=3&block=1&cscore0=$SQL&score0=12&zone0=BODY&id0=1016&var_name0=password[0][newpassword], client: home-ip, server: domain.com, request: "PUT /ghost/api/v0.1/users/password/ HTTP/1.1", host: "domain.com", referrer: "http://domain.com/ghost/team/me/"`

**Comment by hwdsl2** [comment]
@habnai Edit `/etc/nginx/mysite.rules` and append this line:

```
BasicRule  wl:0 "mz:$URL_X:^/ghost/api/v[0-9]+\.[0-9]+/users/password/$|BODY";
```

Restart Nginx:

```
service nginx restart
```

Then try changing your password again.
