### ISSUE TITLE
I can't find the path of nginx conf.

### ISSUE THREAD

**Issue by catmangox** [hwdsl2/setup-ghost-blog#14]
I can't find the path of ngnix conf. It's hard for us to upload the ssl certification bought from third part provider.

**Comment by hwdsl2** [comment]
@Skyepose Hello! The nginx main configuration file is `/opt/nginx/conf/nginx.conf`. Individual blog configurations are stored in `/opt/nginx/conf/nginx-blog1.conf`, etc. To add SSL certs, just edit this file. Then restart Nginx with:
```
service nginx restart
```
