### ISSUE TITLE
这个ghost 默认是安装到哪个路径？

### ISSUE THREAD

**Issue by sbbbsbbb** [hwdsl2/setup-ghost-blog#15]

**Comment by hwdsl2** [comment]
你好！Ghost博客默认安装到 /var/www/你的博客域名。另外，Nginx日志保存在 /opt/nginx/logs, 配置文件保存在 /opt/nginx/conf. 请参见安装完成后显示的说明。

**Comment by sbbbsbbb** [comment]
谢谢！
