### ISSUE TITLE
Restart not working

### ISSUE THREAD

**Issue by ghost** [hwdsl2/setup-ghost-blog#16]
I get: nfo:    No forever processes running
-su: ./starter.sh: No such file or directory

 after :
su - $ghost_user -s /bin/bash -c 'forever stopall; ./starter.sh'

**Comment by hwdsl2** [comment]
@fr0tzed Your command is not correct. Replace `$ghost_user` with `ghost`:

```
su - ghost -s /bin/bash -c 'forever stopall; ./starter.sh'
```
